/**
 * HTML Dashboard Generator
 *
 * Creates interactive, single-file HTML dashboard with:
 * - 5 tabbed sections (Dashboard, Expense Analysis, Haul Log, Optimization, Contract)
 * - Chart.js visualizations (pie, bar, line charts)
 * - Responsive design (mobile-friendly)
 * - Filterable data tables
 * - Print-friendly styling
 *
 * Output: Self-contained HTML file with embedded CSS/JS
 */

import type {
  WasteWiseAnalyticsCompleteResult,
  ProjectRow,
  InvoiceDataRow,
  HaulLogRow,
} from '@/lib/skills/types'
import { logger } from '@/lib/observability/logger'

export interface HtmlGeneratorInput {
  result: WasteWiseAnalyticsCompleteResult
  project: ProjectRow
  invoices: InvoiceDataRow[]
  haulLogs?: HaulLogRow[]
}

export interface HtmlGeneratorOutput {
  html: string
  size: number
  filename: string
  metadata: {
    generatedAt: string
    tabsIncluded: string[]
  }
}

/**
 * Generate interactive HTML dashboard
 */
export async function generateHtmlDashboard(
  input: HtmlGeneratorInput
): Promise<HtmlGeneratorOutput> {
  const startTime = Date.now()

  logger.info('Starting HTML dashboard generation', {
    projectId: input.project.id,
    propertyName: input.project.property_name,
  })

  try {
    const tabsIncluded: string[] = ['Dashboard', 'Expense Analysis', 'Optimization']

    // Add haul log tab for compactor projects
    if (input.project.equipment_type === 'COMPACTOR' && input.haulLogs && input.haulLogs.length > 0) {
      tabsIncluded.push('Haul Log')
    }

    // Add contract tab if available
    if (input.result.contractTerms && input.result.contractTerms.contracts.length > 0) {
      tabsIncluded.push('Contract Terms')
    }

    // Generate HTML content
    const html = generateHtmlContent(input, tabsIncluded)

    const executionTime = Date.now() - startTime
    const filename = generateFilename(input.project)

    logger.info('HTML dashboard generation complete', {
      projectId: input.project.id,
      size: html.length,
      executionTime,
    })

    return {
      html,
      size: html.length,
      filename,
      metadata: {
        generatedAt: new Date().toISOString(),
        tabsIncluded,
      },
    }
  } catch (error) {
    logger.error('HTML dashboard generation failed', error as Error, {
      projectId: input.project.id,
    })
    throw new Error(
      `Failed to generate HTML dashboard: ${error instanceof Error ? error.message : 'Unknown error'}`
    )
  }
}

/**
 * Generate complete HTML content
 */
function generateHtmlContent(input: HtmlGeneratorInput, tabsIncluded: string[]): string {
  const { result, project, invoices, haulLogs } = input

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';">
    <title>WasteWise Analysis - ${escapeHtml(project.property_name)}</title>

    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>

    <style>
        ${generateCSS()}
    </style>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <header class="header">
            <div class="header-content">
                <h1>WasteWise Analysis</h1>
                <p class="subtitle">${escapeHtml(project.property_name)}</p>
                <p class="date">Generated on ${new Date().toLocaleDateString('en-US', {
                  month: 'long',
                  day: 'numeric',
                  year: 'numeric',
                })}</p>
            </div>
            <div class="header-actions">
                <button onclick="window.print()" class="btn-print">Print Report</button>
            </div>
        </header>

        <!-- Tab Navigation -->
        <nav class="tabs">
            ${tabsIncluded
              .map(
                (tab, index) => `
                <button class="tab-btn ${index === 0 ? 'active' : ''}" onclick="showTab('${tab.toLowerCase().replace(/\s+/g, '-')}')">${tab}</button>
            `
              )
              .join('')}
        </nav>

        <!-- Tab Content -->
        <div class="tab-content">
            ${generateDashboardTab(result, project)}
            ${generateExpenseAnalysisTab(result, invoices)}
            ${input.project.equipment_type === 'COMPACTOR' && haulLogs && haulLogs.length > 0 ? generateHaulLogTab(haulLogs, project) : ''}
            ${generateOptimizationTab(result)}
            ${result.contractTerms && result.contractTerms.contracts.length > 0 ? generateContractTermsTab(result.contractTerms) : ''}
        </div>

        <!-- Footer -->
        <footer class="footer">
            <p>🤖 Generated by <strong>WasteWise by THE Trash Hub</strong></p>
            <p class="footer-note">This report contains confidential information. Distribution should be limited to authorized personnel.</p>
        </footer>
    </div>

    <script>
        ${generateJavaScript(result, invoices, haulLogs || [])}
    </script>
</body>
</html>`
}

/**
 * Generate CSS styles
 */
function generateCSS(): string {
  return `
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        :root {
            --primary: #0F766E;
            --primary-light: #5EEAD4;
            --primary-dark: #134E4A;
            --accent: #F59E0B;
            --success: #10B981;
            --warning: #F59E0B;
            --danger: #EF4444;
            --gray-50: #F9FAFB;
            --gray-100: #F3F4F6;
            --gray-200: #E5E7EB;
            --gray-300: #D1D5DB;
            --gray-600: #4B5563;
            --gray-800: #1F2937;
            --gray-900: #111827;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: var(--gray-800);
            background: var(--gray-50);
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
        }

        /* Header */
        .header {
            background: linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%);
            color: white;
            padding: 40px;
            border-radius: 12px;
            margin-bottom: 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .header h1 {
            font-size: 2.5rem;
            margin-bottom: 8px;
        }

        .header .subtitle {
            font-size: 1.25rem;
            opacity: 0.95;
            margin-bottom: 4px;
        }

        .header .date {
            font-size: 0.9rem;
            opacity: 0.8;
        }

        .btn-print {
            background: white;
            color: var(--primary);
            border: none;
            padding: 12px 24px;
            border-radius: 8px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s;
        }

        .btn-print:hover {
            background: var(--gray-100);
            transform: translateY(-2px);
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
        }

        /* Tabs */
        .tabs {
            display: flex;
            gap: 8px;
            margin-bottom: 30px;
            flex-wrap: wrap;
        }

        .tab-btn {
            padding: 12px 24px;
            background: white;
            border: 2px solid var(--gray-200);
            border-radius: 8px;
            cursor: pointer;
            font-weight: 600;
            color: var(--gray-600);
            transition: all 0.2s;
        }

        .tab-btn:hover {
            border-color: var(--primary);
            color: var(--primary);
        }

        .tab-btn.active {
            background: var(--primary);
            border-color: var(--primary);
            color: white;
        }

        /* Tab Panels */
        .tab-panel {
            display: none;
            animation: fadeIn 0.3s;
        }

        .tab-panel.active {
            display: block;
        }

        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }

        /* Cards */
        .card {
            background: white;
            border-radius: 12px;
            padding: 24px;
            margin-bottom: 24px;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }

        .card-header {
            font-size: 1.5rem;
            font-weight: 700;
            color: var(--primary);
            margin-bottom: 20px;
            padding-bottom: 12px;
            border-bottom: 2px solid var(--gray-200);
        }

        /* Grid Layout */
        .grid {
            display: grid;
            gap: 24px;
        }

        .grid-cols-2 {
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
        }

        .grid-cols-3 {
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        }

        /* Metric Cards */
        .metric-card {
            background: linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%);
            color: white;
            padding: 24px;
            border-radius: 12px;
            text-align: center;
        }

        .metric-card.success {
            background: linear-gradient(135deg, var(--success) 0%, #059669 100%);
        }

        .metric-card.warning {
            background: linear-gradient(135deg, var(--warning) 0%, #D97706 100%);
        }

        .metric-label {
            font-size: 0.9rem;
            opacity: 0.9;
            margin-bottom: 8px;
        }

        .metric-value {
            font-size: 2.5rem;
            font-weight: 700;
        }

        .metric-subtitle {
            font-size: 0.85rem;
            opacity: 0.8;
            margin-top: 4px;
        }

        /* Tables */
        .table-container {
            overflow-x: auto;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        thead {
            background: var(--primary);
            color: white;
        }

        th {
            padding: 16px;
            text-align: left;
            font-weight: 600;
        }

        td {
            padding: 12px 16px;
            border-bottom: 1px solid var(--gray-200);
        }

        tbody tr:hover {
            background: var(--gray-50);
        }

        tbody tr:nth-child(even) {
            background: var(--gray-50);
        }

        tbody tr:nth-child(even):hover {
            background: var(--gray-100);
        }

        /* Charts */
        .chart-container {
            position: relative;
            height: 350px;
            margin: 20px 0;
        }

        .chart-container.small {
            height: 250px;
        }

        /* Badges */
        .badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 0.85rem;
            font-weight: 600;
        }

        .badge.success {
            background: #D1FAE5;
            color: var(--success);
        }

        .badge.warning {
            background: #FEF3C7;
            color: var(--warning);
        }

        .badge.danger {
            background: #FEE2E2;
            color: var(--danger);
        }

        .badge.info {
            background: #DBEAFE;
            color: #3B82F6;
        }

        /* Recommendation Cards */
        .recommendation {
            background: var(--gray-50);
            border-left: 4px solid var(--primary);
            padding: 20px;
            margin: 16px 0;
            border-radius: 8px;
        }

        .recommendation.high-priority {
            border-left-color: var(--danger);
        }

        .recommendation-title {
            font-weight: 700;
            font-size: 1.1rem;
            margin-bottom: 8px;
            color: var(--gray-900);
        }

        .recommendation-description {
            color: var(--gray-600);
            margin-bottom: 12px;
        }

        .recommendation-savings {
            font-size: 1.25rem;
            font-weight: 700;
            color: var(--success);
        }

        /* Footer */
        .footer {
            text-align: center;
            padding: 40px 20px;
            color: var(--gray-600);
            border-top: 2px solid var(--gray-200);
            margin-top: 40px;
        }

        .footer-note {
            font-size: 0.85rem;
            margin-top: 8px;
            opacity: 0.7;
        }

        /* Print Styles */
        @media print {
            body {
                background: white;
            }

            .container {
                max-width: 100%;
                padding: 0;
            }

            .header-actions,
            .tabs {
                display: none;
            }

            .tab-panel {
                display: block !important;
                page-break-after: always;
            }

            .card {
                box-shadow: none;
                border: 1px solid var(--gray-300);
                page-break-inside: avoid;
            }
        }

        /* Responsive */
        @media (max-width: 768px) {
            .header {
                flex-direction: column;
                text-align: center;
            }

            .header h1 {
                font-size: 1.75rem;
            }

            .metric-value {
                font-size: 2rem;
            }

            .grid-cols-2,
            .grid-cols-3 {
                grid-template-columns: 1fr;
            }
        }
    `
}

/**
 * Generate Dashboard tab (Executive Summary)
 */
function generateDashboardTab(result: WasteWiseAnalyticsCompleteResult, project: ProjectRow): string {
  const costPerDoor = result.summary.currentMonthlyCost / project.units
  const yardsPerDoor = 2.0 // Placeholder - would calculate from actual data

  return `
        <div id="dashboard" class="tab-panel active">
            <div class="grid grid-cols-3">
                <div class="metric-card">
                    <div class="metric-label">Total Monthly Cost</div>
                    <div class="metric-value">$${formatNumber(result.summary.currentMonthlyCost)}</div>
                    <div class="metric-subtitle">${project.units} units</div>
                </div>
                <div class="metric-card success">
                    <div class="metric-label">Potential Savings</div>
                    <div class="metric-value">$${formatNumber(result.summary.totalSavingsPotential)}/yr</div>
                    <div class="metric-subtitle">${formatNumber(result.summary.savingsPercentage)}% reduction</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Cost Per Door</div>
                    <div class="metric-value">$${formatNumber(costPerDoor)}</div>
                    <div class="metric-subtitle">Monthly</div>
                </div>
            </div>

            <div class="grid grid-cols-2">
                <div class="card">
                    <h2 class="card-header">Property Information</h2>
                    <table>
                        <tbody>
                            <tr><td><strong>Property</strong></td><td>${escapeHtml(project.property_name)}</td></tr>
                            <tr><td><strong>Units</strong></td><td>${project.units}</td></tr>
                            <tr><td><strong>Type</strong></td><td>${escapeHtml(project.property_type || 'N/A')}</td></tr>
                            <tr><td><strong>Equipment</strong></td><td>${escapeHtml(project.equipment_type || 'N/A')}</td></tr>
                            <tr><td><strong>Analysis Period</strong></td><td>${result.summary.dateRange.start} to ${result.summary.dateRange.end}</td></tr>
                        </tbody>
                    </table>
                </div>

                <div class="card">
                    <h2 class="card-header">Savings Breakdown</h2>
                    <div class="chart-container small">
                        <canvas id="savingsChart"></canvas>
                    </div>
                </div>
            </div>

            <div class="card">
                <h2 class="card-header">Top Recommendations</h2>
                ${result.recommendations
                  .filter((r) => r.recommend)
                  .sort((a, b) => a.priority - b.priority)
                  .slice(0, 3)
                  .map(
                    (rec) => `
                    <div class="recommendation ${rec.priority === 1 ? 'high-priority' : ''}">
                        <div class="recommendation-title">${escapeHtml(rec.title)}</div>
                        <div class="recommendation-description">${escapeHtml(rec.description)}</div>
                        ${rec.savings ? `<div class="recommendation-savings">Annual Savings: $${formatNumber(rec.savings)}</div>` : ''}
                    </div>
                `
                  )
                  .join('')}
                ${result.recommendations.filter((r) => r.recommend).length === 0 ? '<p>No optimization recommendations at this time.</p>' : ''}
            </div>
        </div>
    `
}

/**
 * Generate Expense Analysis tab
 */
function generateExpenseAnalysisTab(
  result: WasteWiseAnalyticsCompleteResult,
  invoices: InvoiceDataRow[]
): string {
  return `
        <div id="expense-analysis" class="tab-panel">
            <div class="card">
                <h2 class="card-header">Monthly Expense Trend</h2>
                <div class="chart-container">
                    <canvas id="expenseTrendChart"></canvas>
                </div>
            </div>

            <div class="grid grid-cols-2">
                <div class="card">
                    <h2 class="card-header">Charges by Category</h2>
                    <div class="chart-container small">
                        <canvas id="chargesCategoryChart"></canvas>
                    </div>
                </div>

                <div class="card">
                    <h2 class="card-header">Key Metrics</h2>
                    <table>
                        <tbody>
                            <tr><td><strong>Total Invoices</strong></td><td>${result.summary.totalInvoices}</td></tr>
                            <tr><td><strong>Average Monthly</strong></td><td>$${formatNumber(result.summary.currentMonthlyCost)}</td></tr>
                            <tr><td><strong>Analysis Period</strong></td><td>${calculateMonths(result.summary.dateRange.start, result.summary.dateRange.end)} months</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="card">
                <h2 class="card-header">Invoice History</h2>
                <div class="table-container">
                    <table>
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Invoice #</th>
                                <th>Vendor</th>
                                <th>Tonnage</th>
                                <th>Hauls</th>
                                <th>Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${invoices
                              .sort((a, b) => new Date(b.invoice_date).getTime() - new Date(a.invoice_date).getTime())
                              .map(
                                (inv) => `
                                <tr>
                                    <td>${new Date(inv.invoice_date).toLocaleDateString()}</td>
                                    <td>${escapeHtml(inv.invoice_number || 'N/A')}</td>
                                    <td>${escapeHtml(inv.vendor_name)}</td>
                                    <td>${inv.tonnage ? formatNumber(inv.tonnage) : '-'}</td>
                                    <td>${inv.hauls || '-'}</td>
                                    <td>$${formatNumber(inv.total_amount)}</td>
                                </tr>
                            `
                              )
                              .join('')}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    `
}

/**
 * Generate Haul Log tab (compactor only)
 */
function generateHaulLogTab(haulLogs: HaulLogRow[], project: ProjectRow): string {
  const avgTonnage =
    haulLogs.reduce((sum, h) => sum + (h.tonnage || 0), 0) / haulLogs.length
  const targetCapacity = 8.5

  return `
        <div id="haul-log" class="tab-panel">
            <div class="grid grid-cols-3">
                <div class="metric-card">
                    <div class="metric-label">Total Hauls</div>
                    <div class="metric-value">${haulLogs.length}</div>
                </div>
                <div class="metric-card ${avgTonnage >= 6.0 ? 'success' : 'warning'}">
                    <div class="metric-label">Avg Tons/Haul</div>
                    <div class="metric-value">${formatNumber(avgTonnage)}</div>
                    <div class="metric-subtitle">Target: ${targetCapacity} tons</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Capacity Utilization</div>
                    <div class="metric-value">${formatNumber((avgTonnage / targetCapacity) * 100)}%</div>
                </div>
            </div>

            <div class="card">
                <h2 class="card-header">Tonnage Trend</h2>
                <div class="chart-container">
                    <canvas id="haulTrendChart"></canvas>
                </div>
            </div>

            <div class="card">
                <h2 class="card-header">Haul History</h2>
                <div class="table-container">
                    <table>
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Tonnage</th>
                                <th>Days Since Last</th>
                                <th>Utilization</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${haulLogs
                              .sort((a, b) => new Date(b.haul_date).getTime() - new Date(a.haul_date).getTime())
                              .map((haul) => {
                                const tonnage = haul.tonnage || 0
                                const utilization = (tonnage / targetCapacity) * 100
                                const status =
                                  utilization >= 85 ? 'success' : utilization >= 70 ? 'info' : 'warning'
                                const statusText =
                                  utilization >= 85 ? 'Optimal' : utilization >= 70 ? 'Good' : 'Low'

                                return `
                                <tr>
                                    <td>${new Date(haul.haul_date).toLocaleDateString()}</td>
                                    <td>${formatNumber(tonnage)} tons</td>
                                    <td>${haul.days_since_last || '-'} days</td>
                                    <td>${formatNumber(utilization)}%</td>
                                    <td><span class="badge ${status}">${statusText}</span></td>
                                </tr>
                            `
                              })
                              .join('')}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    `
}

/**
 * Generate Optimization tab
 */
function generateOptimizationTab(result: WasteWiseAnalyticsCompleteResult): string {
  const recommended = result.recommendations.filter((r) => r.recommend)

  return `
        <div id="optimization" class="tab-panel">
            <div class="card">
                <h2 class="card-header">Savings Summary</h2>
                <div class="grid grid-cols-2">
                    <div class="metric-card success">
                        <div class="metric-label">Total Annual Savings</div>
                        <div class="metric-value">$${formatNumber(result.summary.totalSavingsPotential)}</div>
                        <div class="metric-subtitle">${formatNumber(result.summary.savingsPercentage)}% of current spend</div>
                    </div>
                    <div class="metric-card">
                        <div class="metric-label">Recommended Actions</div>
                        <div class="metric-value">${recommended.length}</div>
                        <div class="metric-subtitle">out of ${result.recommendations.length} evaluated</div>
                    </div>
                </div>
            </div>

            <div class="card">
                <h2 class="card-header">Recommended Opportunities</h2>
                ${recommended
                  .sort((a, b) => a.priority - b.priority)
                  .map(
                    (rec) => `
                    <div class="recommendation ${rec.priority <= 2 ? 'high-priority' : ''}">
                        <div style="display: flex; justify-content: space-between; align-items: start;">
                            <div style="flex: 1;">
                                <div class="recommendation-title">
                                    ${escapeHtml(rec.title)}
                                    <span class="badge info">Priority ${rec.priority}</span>
                                    ${rec.confidence ? `<span class="badge ${rec.confidence === 'HIGH' ? 'success' : rec.confidence === 'MEDIUM' ? 'warning' : 'info'}">${rec.confidence}</span>` : ''}
                                </div>
                                <div class="recommendation-description">${escapeHtml(rec.description)}</div>
                                ${rec.implementation ? `<p style="margin-top: 8px; font-size: 0.9rem;"><strong>Implementation:</strong> ${escapeHtml(rec.implementation)}</p>` : ''}
                            </div>
                            ${rec.savings ? `<div class="recommendation-savings" style="margin-left: 20px; text-align: right; white-space: nowrap;">$${formatNumber(rec.savings)}/yr</div>` : ''}
                        </div>
                    </div>
                `
                  )
                  .join('')}
                ${recommended.length === 0 ? '<p>No optimization recommendations at this time.</p>' : ''}
            </div>

            ${result.compactorOptimization && result.compactorOptimization.recommend ? generateCompactorOptimizationDetails(result.compactorOptimization) : ''}

            ${result.leaseUpDetected ? `
            <div class="card" style="background: #FEF3C7; border-left: 4px solid var(--warning);">
                <h3 style="color: var(--warning); margin-bottom: 12px;">⚠️ Lease-Up Property Detected</h3>
                <p>This property appears to be in lease-up (waste generation significantly below benchmarks). Optimization recommendations should be re-evaluated once occupancy stabilizes.</p>
            </div>
            ` : ''}
        </div>
    `
}

/**
 * Generate compactor optimization details
 */
function generateCompactorOptimizationDetails(optimization: any): string {
  return `
        <div class="card">
            <h2 class="card-header">Compactor Optimization - Detailed Breakdown</h2>
            <div class="grid grid-cols-2">
                <table>
                    <tbody>
                        <tr><td><strong>Current Avg Tons/Haul</strong></td><td>${formatNumber(optimization.avgTonsPerHaul)}</td></tr>
                        <tr><td><strong>Target Tons/Haul</strong></td><td>${formatNumber(optimization.targetTonsPerHaul)}</td></tr>
                        <tr><td><strong>Current Annual Hauls</strong></td><td>${optimization.currentAnnualHauls}</td></tr>
                        <tr><td><strong>Optimized Annual Hauls</strong></td><td>${optimization.optimizedAnnualHauls}</td></tr>
                        <tr><td><strong>Hauls Eliminated</strong></td><td>${optimization.haulsEliminated}</td></tr>
                    </tbody>
                </table>
                <table>
                    <tbody>
                        <tr><td><strong>Gross Annual Savings</strong></td><td>$${formatNumber(optimization.grossAnnualSavings)}</td></tr>
                        <tr><td><strong>Net Year 1 Savings</strong></td><td>$${formatNumber(optimization.netYear1Savings)}</td></tr>
                        <tr><td><strong>Net Annual (Year 2+)</strong></td><td>$${formatNumber(optimization.netAnnualSavingsYear2Plus)}</td></tr>
                        <tr><td><strong>ROI</strong></td><td>${formatNumber(optimization.roiPercent)}%</td></tr>
                        <tr><td><strong>Payback Period</strong></td><td>${optimization.paybackMonths} months</td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    `
}

/**
 * Generate Contract Terms tab
 */
function generateContractTermsTab(contractResult: any): string {
  const contract = contractResult.contracts[0]

  return `
        <div id="contract-terms" class="tab-panel">
            <div class="card">
                <h2 class="card-header">Contract Overview</h2>
                <div class="grid grid-cols-2">
                    <table>
                        <tbody>
                            <tr><td><strong>Property</strong></td><td>${escapeHtml(contract.property.name)}</td></tr>
                            <tr><td><strong>Vendor</strong></td><td>${escapeHtml(contract.vendor.name)}</td></tr>
                            <tr><td><strong>Effective Date</strong></td><td>${new Date(contract.contractDates.effectiveDate).toLocaleDateString()}</td></tr>
                            <tr><td><strong>Expiration Date</strong></td><td>${new Date(contract.contractDates.expirationDate).toLocaleDateString()}</td></tr>
                            <tr><td><strong>Term Length</strong></td><td>${contract.contractDates.termMonths} months</td></tr>
                            <tr><td><strong>Auto-Renewal</strong></td><td>${contract.contractDates.autoRenew ? 'Yes' : 'No'}</td></tr>
                        </tbody>
                    </table>
                    <table>
                        <tbody>
                            ${contract.pricing.monthlyBase ? `<tr><td><strong>Monthly Base</strong></td><td>$${formatNumber(contract.pricing.monthlyBase)}</td></tr>` : ''}
                            ${contract.pricing.perPickup ? `<tr><td><strong>Per Pickup</strong></td><td>$${formatNumber(contract.pricing.perPickup)}</td></tr>` : ''}
                            ${contract.pricing.perTon ? `<tr><td><strong>Per Ton</strong></td><td>$${formatNumber(contract.pricing.perTon)}</td></tr>` : ''}
                            <tr><td><strong>Termination Notice</strong></td><td>${contract.terms.terminationNoticeDays} days</td></tr>
                            <tr><td><strong>Payment Terms</strong></td><td>${escapeHtml(contract.terms.paymentTerms)}</td></tr>
                            <tr><td><strong>Insurance Required</strong></td><td>${contract.terms.insuranceRequired ? 'Yes' : 'No'}</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>

            ${contract.services && contract.services.length > 0 ? `
            <div class="card">
                <h2 class="card-header">Service Details</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Container Type</th>
                            <th>Size</th>
                            <th>Frequency</th>
                            <th>Service Days</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${contract.services.map((svc: any) => `
                        <tr>
                            <td>${escapeHtml(svc.containerType)}</td>
                            <td>${svc.containerSize} yards</td>
                            <td>${escapeHtml(svc.frequency)}</td>
                            <td>${escapeHtml(svc.serviceDays || 'N/A')}</td>
                        </tr>
                        `).join('')}
                    </tbody>
                </table>
            </div>
            ` : ''}

            <div class="card">
                <h2 class="card-header">⏰ Important Reminders</h2>
                <div class="recommendation">
                    <strong>90 days before expiration:</strong> Begin contract renewal negotiation or vendor RFP process
                </div>
                <div class="recommendation">
                    <strong>30 days before expiration:</strong> Finalize contract renewal or transition plan
                </div>
                <div class="recommendation">
                    <strong>7 days before expiration:</strong> Confirm service transition or renewal is complete
                </div>
            </div>
        </div>
    `
}

/**
 * Generate JavaScript for interactivity and charts
 */
function generateJavaScript(
  result: WasteWiseAnalyticsCompleteResult,
  invoices: InvoiceDataRow[],
  haulLogs: HaulLogRow[]
): string {
  return `
        // Tab switching
        function showTab(tabId) {
            // Hide all tabs
            document.querySelectorAll('.tab-panel').forEach(panel => {
                panel.classList.remove('active');
            });

            // Remove active from all buttons
            document.querySelectorAll('.tab-btn').forEach(btn => {
                btn.classList.remove('active');
            });

            // Show selected tab
            const selectedTab = document.getElementById(tabId);
            if (selectedTab) {
                selectedTab.classList.add('active');
            }

            // Activate button
            event.target.classList.add('active');
        }

        // Initialize charts when page loads
        window.addEventListener('DOMContentLoaded', function() {
            initializeCharts();
        });

        function initializeCharts() {
            // Savings breakdown pie chart
            const savingsCtx = document.getElementById('savingsChart');
            if (savingsCtx) {
                new Chart(savingsCtx, {
                    type: 'pie',
                    data: {
                        labels: ${safeJsonStringify(result.recommendations.filter((r) => r.recommend && r.savings).map((r) => r.title))},
                        datasets: [{
                            data: ${safeJsonStringify(result.recommendations.filter((r) => r.recommend && r.savings).map((r) => r.savings))},
                            backgroundColor: [
                                '#10B981',
                                '#F59E0B',
                                '#3B82F6',
                                '#8B5CF6',
                                '#EC4899'
                            ]
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                position: 'bottom'
                            }
                        }
                    }
                });
            }

            // Expense trend line chart
            const expenseCtx = document.getElementById('expenseTrendChart');
            if (expenseCtx) {
                const sortedInvoices = ${safeJsonStringify(
                  invoices
                    .sort((a, b) => new Date(a.invoice_date).getTime() - new Date(b.invoice_date).getTime())
                    .map((inv) => ({
                      date: inv.invoice_date,
                      amount: inv.total_amount,
                    }))
                )};

                new Chart(expenseCtx, {
                    type: 'line',
                    data: {
                        labels: sortedInvoices.map(inv => new Date(inv.date).toLocaleDateString()),
                        datasets: [{
                            label: 'Invoice Amount',
                            data: sortedInvoices.map(inv => inv.amount),
                            borderColor: '#0F766E',
                            backgroundColor: 'rgba(15, 118, 110, 0.1)',
                            tension: 0.4,
                            fill: true
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                display: false
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                ticks: {
                                    callback: function(value) {
                                        return '$' + value.toLocaleString();
                                    }
                                }
                            }
                        }
                    }
                });
            }

            // Charges category pie chart
            const chargesCtx = document.getElementById('chargesCategoryChart');
            if (chargesCtx) {
                // Calculate charges summary from invoices
                const chargesSummary = {
                    disposal: 0,
                    pickup_fees: 0,
                    rental: 0,
                    contamination: 0,
                    bulk_service: 0,
                    other: 0
                };

                ${safeJsonStringify(invoices)}.forEach(inv => {
                    if (inv.charges) {
                        chargesSummary.disposal += inv.charges.disposal || 0;
                        chargesSummary.pickup_fees += inv.charges.pickup_fees || 0;
                        chargesSummary.rental += inv.charges.rental || 0;
                        chargesSummary.contamination += inv.charges.contamination || 0;
                        chargesSummary.bulk_service += inv.charges.bulk_service || 0;
                        chargesSummary.other += inv.charges.other || 0;
                    }
                });

                new Chart(chargesCtx, {
                    type: 'doughnut',
                    data: {
                        labels: ['Disposal', 'Pickup Fees', 'Rental', 'Contamination', 'Bulk Service', 'Other'],
                        datasets: [{
                            data: [
                                chargesSummary.disposal,
                                chargesSummary.pickup_fees,
                                chargesSummary.rental,
                                chargesSummary.contamination,
                                chargesSummary.bulk_service,
                                chargesSummary.other
                            ],
                            backgroundColor: [
                                '#10B981',
                                '#3B82F6',
                                '#8B5CF6',
                                '#EF4444',
                                '#F59E0B',
                                '#6B7280'
                            ]
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                position: 'bottom'
                            }
                        }
                    }
                });
            }

            // Haul trend chart
            const haulCtx = document.getElementById('haulTrendChart');
            if (haulCtx) {
                const sortedHauls = ${safeJsonStringify(
                  haulLogs
                    .sort((a, b) => new Date(a.haul_date).getTime() - new Date(b.haul_date).getTime())
                    .map((h) => ({
                      date: h.haul_date,
                      tonnage: h.tonnage || 0,
                    }))
                )};

                new Chart(haulCtx, {
                    type: 'line',
                    data: {
                        labels: sortedHauls.map(h => new Date(h.date).toLocaleDateString()),
                        datasets: [{
                            label: 'Tonnage',
                            data: sortedHauls.map(h => h.tonnage),
                            borderColor: '#0F766E',
                            backgroundColor: 'rgba(15, 118, 110, 0.1)',
                            tension: 0.4,
                            fill: true
                        }, {
                            label: 'Target Capacity (8.5 tons)',
                            data: sortedHauls.map(() => 8.5),
                            borderColor: '#10B981',
                            borderDash: [5, 5],
                            borderWidth: 2,
                            pointRadius: 0
                        }, {
                            label: 'Optimization Threshold (6.0 tons)',
                            data: sortedHauls.map(() => 6.0),
                            borderColor: '#F59E0B',
                            borderDash: [5, 5],
                            borderWidth: 2,
                            pointRadius: 0
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                position: 'bottom'
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                title: {
                                    display: true,
                                    text: 'Tons'
                                }
                            }
                        }
                    }
                });
            }
        }
    `
}

/**
 * Generate filename
 */
function generateFilename(project: ProjectRow): string {
  const propertyName = project.property_name
    .replace(/[^a-zA-Z0-9]/g, '_')
    .replace(/_+/g, '_')
    .substring(0, 50)

  const date = new Date().toISOString().split('T')[0]

  return `WasteWise_Dashboard_${propertyName}_${date}.html`
}

/**
 * Utility functions
 */
function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  }
  return text.replace(/[&<>"']/g, (m) => map[m])
}

/**
 * Safely embed JSON in JavaScript context
 * Prevents XSS by escaping </script> and other dangerous sequences
 */
function safeJsonStringify(data: unknown): string {
  return JSON.stringify(data)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/\//g, '\\u002f')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
}

function formatNumber(num: number): string {
  return num.toLocaleString('en-US', {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  })
}

function calculateMonths(startDate: string, endDate: string): number {
  const start = new Date(startDate)
  const end = new Date(endDate)
  return Math.max(
    (end.getFullYear() - start.getFullYear()) * 12 + (end.getMonth() - start.getMonth()),
    1
  )
}
